name: Build-Test-Lint-Typecheck

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: create and activate venv
        run: |
          ./ci/linux/create_venv.sh
          ./ci/linux/install_dependencies.sh
      - name: run lint
        run: |
          ./ci/linux/lint.sh

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: create and activate venv
        run: |
          ./ci/linux/create_venv.sh
          ./ci/linux/install_dependencies.sh
      - name: run unit tests
        run: |
          ./ci/linux/test_unit.sh
      - name: surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: create and activate venv
        run: |
          ./ci/linux/create_venv.sh
          ./ci/linux/install_dependencies.sh
      - name: run typechecker
        run: |
          ./ci/linux/typecheck.sh