name: Build-Test-Lint-Typecheck

on: [push]

env:
  JUSTFILE: ${{ github.workspace }}/justfile

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install dependencies
        run: just --justfile "$JUSTFILE" install
      - name: Run linter
        run: just --justfile "$JUSTFILE" lint
      - name: Check formatting
        run: just --justfile "$JUSTFILE" format-check

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install dependencies
        run: just --justfile "$JUSTFILE" install
      - name: Run unit tests
        run: just --justfile "$JUSTFILE" test
      - name: Publish test results
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v2
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install dependencies
        run: just --justfile "$JUSTFILE" install
      - name: Run type checker
        run: just --justfile "$JUSTFILE" typecheck